### PR TITLE
Improve button spacing in specupload

### PR DESCRIPTION
**Pull request by themerekat**
# Pull Request Checklist:
From this:
image

To this:
image

Fixes: https://github.com/BioKIC/Symbiota/issues/1707

# Pre-Approval

- [x] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [x] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [x] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [x] There are no linter errors
- [x] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [x] Comment which GitHub issue(s), if any does this PR address

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

### CODE REVIEW

**Review by GregoryPost — CHANGES_REQUESTED** [review]
I think we are trying to get away from inline styling.  I suggest adding a class to those buttons and then styling the class in main.css

**Comment by themerekat** [comment]
@GregoryPost , the styling is putting them in divs, not in-line with the buttons. Are you saying that we should just add blanket padding to all buttons?

**Comment by GregoryPost** [comment]
Looks like there already is a class that could serve this purpose: .bottom-breathing-room-rel

Example:
`<button class="bottom-breathing-room-rel" type="submit" name="action" value="Automap Fields" >`

**Comment by GregoryPost** [comment]
> @GregoryPost , the styling is putting them in divs, not in-line with the buttons. Are you saying that we should just add blanket padding to all buttons?

No, just updating those buttons with an appropriate css class selector. If you do this you should not need the new divs with inline styling.

**Comment by NikitaSalikov** [comment]
@themerekat, You can also use a smaller gap class: "bottom-breathing-room-rel-sm" which might look more aesthetic.

**Comment by themerekat** [comment]
Still not super sure I like it, because now the Start Upload button is a little askew of these buttons, but it works.

**Review by GregoryPost — APPROVED** [review]

**Pull request merged**
