### PR TITLE
3.1 record search form fixes

### PR DESCRIPTION
**Pull request by Atticus29**
# Description

This PR makes the requested fixes in [this ticket](https://github.com/orgs/BioKIC/projects/6/views/10?pane=issue&itemId=61354349&sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=37442788&sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=Status). Specifically, it makes various aesthetic improvements to the occurrencetabledisplay:

- Makes Entered By, Date Entered, and Date Modified all on the same line (not awkwardly misaligned)
- Puts Sort By, Order By, Record Output on same line
- Unifies spacing between lines
- Changes icon after "Custom Field 1" to a plus sign instead of pencil with lines.

It also changed some translations for the plus sign.

The following look like they were already resolved by previous PRs and/or are related to the form layout that the end user has toggled.

- Put "Display Table" buttons on the same line
- Make sure that Copy Link icon is the same color as the text

# Known Issues

For the following requirement: 

- Change color of buttons -> I confirmed that these buttons are leveraging the styling in main.css:

```
button {
  background-color: var(--darkest-color);
```

, meaning that the portal-owner can modifiy the color in variables.css.

It's possible that the ticket meant that I was supposed to change this to a different color in variables.css (i.e., not "darkest-color")? But, that would affect all buttons portal-wide. Is that desired? I think button colors should be standardized across the product both for a unity of aesthetic and from a code maintainability point of view.

## Before

Screen Shot 2024-04-30 at 11 17 13 AM

## After

Screen Shot 2024-04-30 at 2 09 00 PM

# QA Notes

This branch is deployed live in [https://dev001.symbiota.org/collections/editor/occurrencetabledisplay.php?displayquery=1&collid=12](https://dev001.symbiota.org/collections/editor/occurrencetabledisplay.php?displayquery=1&collid=12)

# Pull Request Checklist:

# Pre-Approval

- [x] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
    - N/A
- [x] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [x] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [x] There are no linter errors
- [ ] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
    - This page does not seem to have any responsive features. Should be a separate ticket.
- [ ] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
    - There is a bit of in-line styling that I added to this. queryForm.php doesn't seem to have a css file of its own nor a <style> element in it. Happy to add one if it feels warranted, but to me it did not.
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
    - N/A
- [x] Comment which GitHub issue(s), if any does this PR address
    - [https://github.com/BioKIC/Symbiota/issues/1188](https://github.com/BioKIC/Symbiota/issues/1188)
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).
    - N/A

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

### CODE REVIEW

**Comment by themerekat** [comment]
@Atticus29 , looks great! I assume occurrenceeditor will be done in a different PR?
Re: changing the colors of the buttons, I think we need to define a new button class that's like "negative button" for things like "delete" and "reset". The default for that could be gray or red or something "negative". What do you think? I had a similar thought in [this PR](https://github.com/BioKIC/Symbiota/pull/1173)

**Comment by Atticus29** [comment]
@themerekat love this idea. As long as the shade is much more subdued (lighter ?) than the primary button color. Otherwise, for instance, we'd have trouble with folks with red-green colorblindness.

Ok if setting up that second color is a separate ticket?

**Comment by Atticus29** [comment]
And yes-occurrence editor would be separate as well.

**Comment by themerekat** [comment]
@Atticus29 , awesome! Then we are good.

**Review by themerekat — APPROVED** [review]

**Pull request merged**
