### PR TITLE
3.1 new search to list display

### PR DESCRIPTION
**Pull request by Atticus29**
# Description

This PR adds radio buttons on the new search page that allow the end user to express a preference between list display or table display for their results. It also handles an edge case I found where the page flow and breadcrumbs were misbehaving when a user toggles between those two result views from their respective result pages. Specifically, it:

- Fixes bug in an edge case where the user navigates from list view to table view or vice versa but they're coming from the new search page. Previously, the breadcrumbs would take them back to harvestparams, but this fixes that misbehavior.
- Adds a section above the search and reset buttons that contains a set of radio buttons for result display format preference.
- Handles the logic of whichever above radio button is selected.
- Adds some translations.

# Before

Screenshot 2024-06-05 at 1 53 17 PM

# After

Screenshot 2024-06-05 at 1 46 18 PM

# QA notes

This is deployed live on [https://dev001.symbiota.org/](https://dev001.symbiota.org/)

# Pull Request Checklist:

# Pre-Approval

- [x] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
    - N/A
- [x] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [x] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [x] There are no linter errors
- [x] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [x] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
    - N/A
- [x] Comment which GitHub issue(s), if any does this PR address
    - [https://github.com/BioKIC/Symbiota/issues/1364](https://github.com/BioKIC/Symbiota/issues/1364)
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).
    - N/A

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

### CODE REVIEW

**Review by themerekat — CHANGES_REQUESTED** [review]
@Atticus29 , I'm finding that navigating back to "Search Collections" via the breadcrumbs from /collections/listtabledisplay.php takes me back to harvestparams...but I thought that's what you fixed? Can you check on that?

**Comment by Atticus29** [comment]
> @Atticus29 , I'm finding that navigating back to "Search Collections" via the breadcrumbs from /collections/listtabledisplay.php takes me back to harvestparams...but I thought that's what you fixed? Can you check on that?

Oh good catch! That's actually _not_ the thing that I fixed, but it's another one that I should. On it asap. Thanks!

**Comment by Atticus29** [comment]
> @Atticus29 , I'm finding that navigating back to "Search Collections" via the breadcrumbs from /collections/listtabledisplay.php takes me back to harvestparams...but I thought that's what you fixed? Can you check on that?

Fixed in ec4050f65. Can't deploy on dev001 rn. because it seems to be down.

**Comment by Atticus29** [comment]
@themerekat dev001.symbiota.org is back up and has been updated. Should be ready for QA again.

**Review by themerekat — APPROVED** [review]
Looks great!

**Pull request merged**
