### PR TITLE
USDA Header refactor

### PR DESCRIPTION
**Pull request by Atticus29**
# Description

This PR implements several fixes related to tickets having to do with the behavior and appearance of the header. It is essentially an entire re-factor of the header, this time modeling the NAL site rather than the ARS site. This refactor solves three problems at once: the header text justification at larger screen sizes, the weird lingering of the dropdown buttons during page load, and the small global font size.

Specifically, it:

- Adds a javaScript file (css/uswds/symbiota/nal.js) that was lifted from the NAL page to implement correct behavior of clicks on the header and banner, etc.
- Removes no-longer-needed assets/uswds/js/ARSbranding.js. ARS styling and js is now no longer used anywhere.
- Removes css/uswds/symbiota/ARSbranding.css for same reason
- Adds two new icons from the NAL site
- Copies sharedCollectionStyling.css over from the /v202209 directory to allow it to diverge from Development if needed. Note that this may not be desired. Worth thinking about
- Increases the global font size via css/uswds/symbiota/main.css.
- Changes some of the margin behavior of the breadcrumbs and innertext divs in light of new styling
- Improves the error handling of said javaScript file above in order to accommodate that fact that we're not using drupal. In other words, there were a bunch of console errors when I first copied this code over to our codebase; I fixed them.
- Changes the styling in css/uswds/symbiota/nalStyleguide.css in order to better fit all of the secondary links in the navbar and to correctly source some of the fonts and images.
- Entirely refactors header.php (see general description above)
## Some concerns that I still have

Changing to font size (or something else that I did??) seems to have removed some margin styling for the inner content of our pages. I'm not mad at the look of it because I think it utilizes more screen space. But I don't love that the breadcrumbs seem to be really out there now haha. Thoughts?

## Appearance of header (and site contents) before changes

Screen Shot 2023-12-20 at 2 57 36 PM

## Appearance of header (and site contents) after changes

Screen Shot 2023-12-20 at 2 56 54 PM

Screen Shot 2023-12-20 at 2 57 57 PM

Screen Shot 2023-12-20 at 2 58 14 PM

# Pull Request Checklist:

# Pre-Approval

- [x] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
    - N/A
- [x] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [ ] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
    - N/A
- [x] There are no linter errors
- [x] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [x] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
    - N/A
- [x] Comment which GitHub issue(s), if any does this PR address
    -  [https://github.com/orgs/BioKIC/projects/6/views/10?pane=issue&itemId=47230290](https://github.com/orgs/BioKIC/projects/6/views/10?pane=issue&itemId=47230290)
    - [https://github.com/orgs/BioKIC/projects/6/views/10?pane=issue&itemId=47991066](https://github.com/orgs/BioKIC/projects/6/views/10?pane=issue&itemId=47991066)
    - [https://github.com/orgs/BioKIC/projects/6/views/10?pane=issue&itemId=48003445](https://github.com/orgs/BioKIC/projects/6/views/10?pane=issue&itemId=48003445)
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).
    - N/A

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

### CODE REVIEW

**Comment by themerekat** [comment]
@Atticus29 , I agree that the breadcrumbs way over on the side is a bit awkward. Going to cc Jenn on this for her take.

**Comment by Atticus29** [comment]
> @Atticus29 , I agree that the breadcrumbs way over on the side is a bit awkward. Going to cc Jenn on this for her take.

@themerekat  to clarify, this would only affect the USDA branch. These changes are not going into the Development branch.
I agree. Let me see what I can do about the breadcrumbs at least and get back to you and Ed.

**Comment by themerekat** [comment]
> > @Atticus29 , I agree that the breadcrumbs way over on the side is a bit awkward. Going to cc Jenn on this for her take.
> 
> @themerekat to clarify, this would only affect the USDA branch. These changes are not going into the Development branch. I agree. Let me see what I can do about the breadcrumbs at least and get back to you and Ed.

AH, well less critical, then. In that case, I think it's fine to move forward.

**Review by themerekat — APPROVED** [review]

**Comment by Atticus29** [comment]
Fixed in ed1071d33

**Pull request merged**
