### PR TITLE
Accessibility mode name change

### PR DESCRIPTION
**Pull request by Atticus29**
# Description

This PR addresses the confusion about the "accessibility mode" button by removing it from the header, renaming it to what it actually does: "switch form layout", and implements it only in the pages that it actually currently affects.

Addresses issue 1042:  [https://github.com/BioKIC/Symbiota/issues/1042](https://github.com/BioKIC/Symbiota/issues/1042)

## Demo

[https://youtu.be/smhSp-VmveE](https://youtu.be/smhSp-VmveE)

## QA

A live instance of this is currently on https://dev001.symbiota.org/, and it's ready for testing.

## Known issues

There is a lot of new inline styling, but it is repetitive. In line (ha!) with current discussions around styling changes and Laravel coming down the line, this didn't feel high-priority. But I'm also in a rush right now, so maybe I'll feel differently tomorrow. Feel welcome to push back on this. 

# Pull Request Checklist:

# Pre-Approval

- [x] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
    - N/A
- [x] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [x] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [x] There are no linter errors
- [x] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [x] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
    - N/A
- [x] Comment which GitHub issue(s), if any does this PR address
    - [https://github.com/BioKIC/Symbiota/issues/1042](https://github.com/BioKIC/Symbiota/issues/1042)
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).
    - N/A

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

### CODE REVIEW

**Comment by themerekat** [comment]
Comment on skeletalsubmit.php: when toggling to accessibility mode, the plus sign icon (to add a new taxon) should go to the right of the scientific name field OR it should be turned into a button (that looks like Add Record) that says "Add New Taxon to Thesaurus"
image

**Comment by themerekat** [comment]
Can there also be a toggle on this page?

https://dev001.symbiota.org/collections/editor/occurrencetabledisplay.php?displayquery=1&collid=34
image

So that it's possible to also see a version closer to the older version of this form?
image

The new version of the form looks unpolished because some of the fields aren't in line with each other. Some (rough) recommendations for the condensed version:
image

**Comment by themerekat** [comment]
The Switch Form Layout doesn't appear in the organic location of fieldstandardization:
image

To get to this view, go to Edit Existing Occurrence Records and click the pencil-with-lines icon in the top right corner of the page.

**Comment by themerekat** [comment]
Another possibility for consideration: what if we brought back the "Accessibility Mode" button, but we make it more obvious what this button does, e.g., by putting a (?) icon next to it that says "Click this button to switch form layouts to ones that contain one input per row". Or it could be a checkbox?
Not sure if this is any better, and I know you've already done a ton of work on this, but it _would_ prevent you from having to add the toggle button to every form you adjust in the future.

**Comment by Atticus29** [comment]
> Another possibility for consideration: what if we brought back the "Accessibility Mode" button, but we make it more obvious what this button does, e.g., by putting a (?) icon next to it that says "Click this button to switch form layouts to ones that contain one input per row". Or it could be a checkbox? Not sure if this is any better, and I know you've already done a ton of work on this, but it _would_ prevent you from having to add the toggle button to every form you adjust in the future.

We _could_ get started on an accessibility menu in the footer.

I think having accessibility stuff in the footer is more common (ironically).

 Check out this website as a great example: [https://partakefoods.com/](https://partakefoods.com/). Note on the bottom left of the screen, there's a whole menu modal that pops up with several different accessibility options to toggle. We could start with just the "Accessible form layout + info. icon" button in a similar menu, and then populate with more as the product matures (in Laravel, for example). Should I try to implement something like that instead?

**Comment by themerekat** [comment]
> > Another possibility for consideration: what if we brought back the "Accessibility Mode" button, but we make it more obvious what this button does, e.g., by putting a (?) icon next to it that says "Click this button to switch form layouts to ones that contain one input per row". Or it could be a checkbox? Not sure if this is any better, and I know you've already done a ton of work on this, but it _would_ prevent you from having to add the toggle button to every form you adjust in the future.
> 
> We _could_ get started on an accessibility menu in the footer.
> 
> I think having accessibility stuff in the footer is more common (ironically).
> 
> Check out this website as a great example: https://partakefoods.com/. Note on the bottom left of the screen, there's a whole menu modal that pops up with several different accessibility options to toggle. We could start with just the "Accessible form layout + info. icon" button in a similar menu, and then populate with more as the product matures (in Laravel, for example). Should I try to implement something like that instead?

YES, exactly! I've seen this on a lot of sites, and it seems to be becoming the norm. It does seem to get in the way sometimes, but if it had some sort of minimize feature, I think this would be a great way to go.

**Comment by Atticus29** [comment]
> > > Another possibility for consideration: what if we brought back the "Accessibility Mode" button, but we make it more obvious what this button does, e.g., by putting a (?) icon next to it that says "Click this button to switch form layouts to ones that contain one input per row". Or it could be a checkbox? Not sure if this is any better, and I know you've already done a ton of work on this, but it _would_ prevent you from having to add the toggle button to every form you adjust in the future.
> > 
> > 
> > We _could_ get started on an accessibility menu in the footer.
> > I think having accessibility stuff in the footer is more common (ironically).
> > Check out this website as a great example: https://partakefoods.com/. Note on the bottom left of the screen, there's a whole menu modal that pops up with several different accessibility options to toggle. We could start with just the "Accessible form layout + info. icon" button in a similar menu, and then populate with more as the product matures (in Laravel, for example). Should I try to implement something like that instead?
> 
> YES, exactly! I've seen this on a lot of sites, and it seems to be becoming the norm. It does seem to get in the way sometimes, but if it had some sort of minimize feature, I think this would be a great way to go.

Awesome! I will do this instead, then!

**Comment by Atticus29** [comment]
Closing because there's consensus about going in a different direction.

**Pull request closed without merging**
