### PR TITLE
Key v1 lang tag fix

### PR DESCRIPTION
**Pull request by themerekat**
Add some missing lang tags that belong to ident/key-v1.php

# Pre-Approval

- [x] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [x] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [ ] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [x] There are no linter errors
- [x] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

### CODE REVIEW

**Review by Atticus29 — COMMENTED** [review]
Not sure if we want a french file as well?
Also, don't forget the spaces between the concatenated `.`.

**Review by Atticus29 — APPROVED** [review]
Left comments, but approving anyway.

**Comment by themerekat** [comment]
@Atticus29 , is it expected that we go back through the file and fix all the spacing, even where we didn't fiddle with the code? I only added one concatenation (which was missing a space, but this has been a trend that many of my PRs get this comment).

**Comment by Atticus29** [comment]
> @Atticus29 , is it expected that we go back through the file and fix all the spacing, even where we didn't fiddle with the code? I only added one concatenation (which was missing a space, but this has been a trend that many of my PRs get this comment).

Hi, @themerekat, Nikita and I have been only implementing the changes on only the lines of code that we touch. So, even if we aren't the source of the issue, if we happen to be in that line of code, may as well update it to the current code convention.

Since I consider this non-essential (but rather just good codebase stewardship), I'll keep approving the PRs whether the improvements get implemented or not.

**Pull request merged**
