### PR TITLE
Collections search fix

### PR DESCRIPTION
**Pull request by NikitaSalikov**
# Changes Made:
removed line that adds category value to collections list which created an issue when category value is the same as some collection's value giving the wrong result.

# Pull Request Checklist:

# Pre-Approval

- [X] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
- [X] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [ ] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [ ] There are no linter errors
- [X] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [X] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
- [X] Comment which GitHub issue(s), if any does this PR address:
https://github.com/BioKIC/Symbiota/issues/1703
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).

# Post-Approval

- [x] It is the code author's responsibility to merge their own pull request after it has been approved
- [x] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [x] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

### CODE REVIEW

**Review by themerekat — APPROVED** [review]

**Review by Atticus29 — COMMENTED** [review]
This seems to work exactly as expected. I kicked the tires around my local machine, looking for reversions (why would I have included `'#search-form-colls input[name="cat[]"]:checked'` ??), and couldn't find any.

On the github issue, Ed mentions that there's still a stlying fix that would need to accompany this (see [https://github.com/BioKIC/Symbiota/issues/1703#issuecomment-2377987756](https://github.com/BioKIC/Symbiota/issues/1703#issuecomment-2377987756)). 

Could I trouble you to implement the js fix as well?

**Comment by NikitaSalikov** [comment]
> This seems to work exactly as expected. I kicked the tires around my local machine, looking for reversions (why would I have included `'#search-form-colls input[name="cat[]"]:checked'` ??), and couldn't find any.
> 
> On the github issue, Ed mentions that there's still a stlying fix that would need to accompany this (see [#1703 (comment)](https://github.com/BioKIC/Symbiota/issues/1703#issuecomment-2377987756)).
> 
> Could I trouble you to implement the js fix as well?

I believe I fixed this. Also fixed the map search issue when deselecting category wouldn't deselect "Select/Deselect all collections" checkbox.

**Review by themerekat — APPROVED** [review]
Seems to be working great!

**Review by Atticus29 — APPROVED** [review]
LGTM!

One lingering issue is that if a user removes a chip in the criteria section, that collection is unchecked in the collections accordion. However, the category checkbox is not also deselected.

It's just an aesthetic issue (the search seems to behave correctly). I'll leave it up to you and @themerekat  whether this needs to be fix in this ticket.

**Comment by NikitaSalikov** [comment]
> LGTM!
> 
> One lingering issue is that if a user removes a chip in the criteria section, that collection is unchecked in the collections accordion. However, the category checkbox is not also deselected.
> 
> It's just an aesthetic issue (the search seems to behave correctly). I'll leave it up to you and @themerekat whether this needs to be fix in this ticket.

@Atticus29, There was an issue with the chips and functions. If I remember correctly the uncheckAll() function in searchform.js is not called by default instead it's the uncheckAll() in js/symb/collections.index.js. I changed the function in searchform.js so that it's called properly and added functionality that you mentioned.

**Comment by themerekat** [comment]
I have re-tested on dev005 and it seems to be working as expected!

**Pull request merged**
