### PR TITLE
Search by association

### PR DESCRIPTION
**Pull request by Atticus29**
# Description

This PR adds a feature to the new search page that allows users to search by any relationship type (including all possible relaionships) and optionally by a relationship with a target taxon. Specifically, it:

- Creates a new AssociationManager class that contains methods for composing the sql statement.
- Adds a lot of new methods to OccurrenceTaxaManager very analogous to how things are processed for the already-existing search-by-taxon. Some of the methods for the new search-by-taxon and by-relationship are split into smaller, pithier sub-methods. An attempt was made generalize these and apply them to the existing search-by-taxon; a few methods were successfully generalized with no impact, but it proved to require more precise surgery than I had bandwidth for on this first pass to generalize all of the methods that ought to be generalized. Point being: things should work, but there is still a lot of redundant code chunks that could be DRYed up in the future. I also tried to move several of these methods to the AssociationManager class - some successfully, and others with too many dependencies on other properties or methods in the OccurrenceTaxaManager class to make it worth it; it was a pass-by-reference cluster****.

- Removes some commented-out code
- Adds translations
- Updates the UI and javascript logic for the new search page, including search fields, remembering the search criteria, and making the criteria chips responsive to the aforementioned UI behaviors. A few of the harder-to-follow js methods were made into pithier, more readible sub-functions.
- Autoformatts js/symb/api.taxonomy.taxasuggest.js

# Known issue

See this video: [https://youtu.be/WKGSFM-6T_g](https://youtu.be/WKGSFM-6T_g).

For the TL:DR version, searching for everything that hasHost of Pinus returns two results. Both of the results technically have a hostOf relationship in the omoccurassociations, but they are correctly returned as results. This demonstrates that the search for the inverse relationship is working.

However, just as an example, I made some random Gelidium purpurascens occurrence have two different pinus occurrences designated as its hosts in my local db.

Searching for everything that is hostOf Gelidium purpurascens only returns one of the two results. The result returned is the one that explicitly has the inverse relationship also recorded in the db:

Screenshot 2024-07-24 at 10 55 55 AM

I think that this highlights the fact that we need to have our end users explicitly rather than implicitly establish the relationship in both directions.

Is this already known?

# Pull Request Checklist:

# Pre-Approval

- [x] There is a description section in the pull request that details what the proposed changes do. It can be very brief if need be, but it ought to exist.
- [ ] Hotfixes should be branched off of the `master` branch and **squash and merged** back into the `master` branch.
    - N/A
- [x] Features and backlog bugs should be merged into the `Development` branch, **NOT** `master`
- [ ] All new text is preferably internationalized (i.e., no end-user-visible text is hard-coded on the PHP pages), and the [spreadsheet tracking internationalizations](https://docs.google.com/spreadsheets/d/133fps9w2pUCEjUA6IGCcQotk7dn9KvepMXJ2IWUZsE8/edit?usp=sharing) has been updated either with a new row or with checkmarks to existing rows.
- [x] There are no linter errors
- [x] New features have responsive design (i.e., look aesthetically pleasing both full screen and with small or mobile screens)
- [x] [Symbiota coding standards](https://docs.google.com/document/d/1-FwCZP5Zu4f-bPwsKeVVsZErytALOJyA2szjbfSUjmc/edit?usp=sharing) have been followed
- [ ] If any files have been reformatted (e.g., by an autoformatter), the reformat is its own, separate commit in the PR
    - js/symb/api.taxonomy.taxasuggest.js was. Not in a separate commit, though. But I don't think that I made any other change to that file.
- [x] Comment which GitHub issue(s), if any does this PR address
    - [https://github.com/BioKIC/Symbiota/issues/1427](https://github.com/BioKIC/Symbiota/issues/1427)
- [ ] If this PR makes any changes that would require additional configuration of any Symbiota portals outside of the files tracked in this repository, make sure that those changes are detailed in [this document](https://docs.google.com/document/d/1T7xbXEf2bjjm-PMrlXpUBa69aTMAIROPXVqJqa2ow_I/edit?usp=sharing).
    - N/A

# Post-Approval

- [ ] It is the code author's responsibility to merge their own pull request after it has been approved
- [ ] If this PR represents a merge into the `Development` branch, remember to use the **squash & merge** option
- [ ] If this PR represents a merge from the `Development` branch into the master branch, remember to use the **merge** option
- [ ] If this PR represents a hotfix into the `master` branch, a subsequent PR from `master` into `Development` should be made **merge** option (i.e., no squash).
- [ ] If the dev team has agreed that this PR represents the last PR going into the `Development` branch before a tagged release (i.e., before an imminent merge into the master branch), make sure to notify the team and [lock the `Development` branch](https://github.com/BioKIC/Symbiota/settings/branches) to prevent accidental merges while QA takes place. Follow the release protocol [here](https://github.com/BioKIC/Symbiota/blob/master/docs/release-protocol.md).
- [ ] Don't forget to delete your feature branch upon merge. Ignore this step as required.

Thanks for contributing and keeping it clean!

### CODE REVIEW

**Comment by themerekat** [comment]
I think people will want to search by associations without having to specify a taxon name. For example, to answer the query:
"What specimens are hosts of other species in this National Forest?"
or
"What specimens have multiple parts?" (i.e., has association type "partOf")

When I try to run this query, it just says "Associations-none"
image

**Comment by themerekat** [comment]
Need all the reciprocal relationships from the relationship table to be included in this dropdown list
image
i.e.,
hostOf
hasPart
etc.

**Comment by Atticus29** [comment]
> Need all the reciprocal relationships from the relationship table to be included in this dropdown list image i.e., hostOf hasPart etc.

Ok. Just to clarify, reciprocal relationships are already being searched. That menu is populated by DISTINCT values in the relationship column of omoccurassociations.

I am happy to add all reciprocal relationships; that's a good idea.

To clarify even further, in the particular case of the db that was used in dev001, if you were to search using hostOf, there would be no results (i.e., we know for a fact that there are no entries in the omoccurassociations table with the hostOf relationship type, because it's not in the dropdown menu) EXCEPT those in the reciprocal hasHost relationship.

You can essentially populate hostOf in that menu by adding such an association.

But I agree... just to make things look better, I'll add reciprocals as well.

**Comment by themerekat** [comment]
I ran a search for Veratrum californicum
ecologicallyOccursWith
Veratrum speciosum
- [x] include synonyms

I expected to find this record: https://dev001.symbiota.org/collections/individual/index.php?occid=2960592
Which is of Veratrum californicum and has an association with Veratrum californicum var. californicum, which is the accepted synonym of Veratrum speciosum.

I did not get any results, which seems to indicate that searching including synonyms is not working as expected.

**Comment by themerekat** [comment]
> > Need all the reciprocal relationships from the relationship table to be included in this dropdown list image i.e., hostOf hasPart etc.
> 
> Ok. Just to clarify, reciprocal relationships are already being searched. That menu is populated by DISTINCT values in the relationship column of omoccurassociations.
> 
> I am happy to add all reciprocal relationships; that's a good idea.
> 
> To clarify even further, in the particular case of the db that was used in dev001, if you were to search using hostOf, there would be no results (i.e., we know for a fact that there are no entries in the omoccurassociations table with the hostOf relationship type, because it's not in the dropdown menu) EXCEPT those in the reciprocal hasHost relationship.
> 
> You can essentially populate hostOf in that menu by adding such an association.
> 
> But I agree... just to make things look better, I'll add reciprocals as well.

Ok, so if I'm understanding this correctly: the reason why it wasn't possible to search for hostOf was because there were no _occurrences_ in the db that is the host of another record, even though there are some records that have "hasHost" relationships?

I.e., all the occurrences with "hasHost" did not link to another occurrence?

**Comment by themerekat** [comment]
I think that people will want to be able to search two taxa without specifying the associationType. Could we add "Any" to the dropdown menu and be able to search across multiple associationTypes?

**Comment by themerekat** [comment]
Things that I tested that work (yay!):
- Search for associations with a taxon name, associationType, association taxon name
- Search for associations with stateProvince value, associationType, association taxon name
- Search for associations with bounding box, associationType, and association taxon name
- Search for associations with taxon name, associationType, association taxon name, trait value
- Conducting a search, then hitting the back button --> the criteria are properly populated

Other notes (not necessarily related to this PR)
- Updated an association's taxonomic name --> the updated taxonomic name was correctly updated in the association

**Comment by Atticus29** [comment]
> > > Need all the reciprocal relationships from the relationship table to be included in this dropdown list image i.e., hostOf hasPart etc.
> > 
> > 
> > Ok. Just to clarify, reciprocal relationships are already being searched. That menu is populated by DISTINCT values in the relationship column of omoccurassociations.
> > I am happy to add all reciprocal relationships; that's a good idea.
> > To clarify even further, in the particular case of the db that was used in dev001, if you were to search using hostOf, there would be no results (i.e., we know for a fact that there are no entries in the omoccurassociations table with the hostOf relationship type, because it's not in the dropdown menu) EXCEPT those in the reciprocal hasHost relationship.
> > You can essentially populate hostOf in that menu by adding such an association.
> > But I agree... just to make things look better, I'll add reciprocals as well.
> 
> Ok, so if I'm understanding this correctly: the reason why it wasn't possible to search for hostOf was because there were no _occurrences_ in the db that is the host of another record, even though there are some records that have "hasHost" relationships?
> 
> I.e., all the occurrences with "hasHost" did not link to another occurrence?

Thank you for asking this question. It helped me realize that we really need that full complement of dropdown choices haha.

All it means is that there is no entry in the omoccurassociations table that has relationship 'hostOf'. It _doesn't_ mean that there are no occurrences with "hasHost" linked to another occurrence; there very well could be. And those occurrences should theoretically be captured in search results.

So, for instance, let's say there's an occurrence of Dendroctonus ponderosae that has a relationship of hasHost attached to another occurrence in the DB of a Pinus longifolia.

If you search for all taxa that hasHost Pinus longifolia, you should find that Dendroctonus ponderosae result.

Similarly, if you search for all taxa that are hostOf Dendroctonus ponderosae, you should find the Pinus longifolia occurrence.

Currently, and this is the bug at hand, if no other, random entry in omoccurassociations happens to explicitly have a hostOf relationship type, this

> if you search for all taxa that are hostOf Dendroctonus ponderosae, you should find the Pinus longifolia occurrence.

search won't be possible, because hostOf won't be the in drop down.

I hope I make sense and am thinking about this correctly. If not, no worries; we're in agreement regardless that this needs to be fixed haha.

**Comment by themerekat** [comment]
> > > > Need all the reciprocal relationships from the relationship table to be included in this dropdown list image i.e., hostOf hasPart etc.
> > > 
> > > 
> > > Ok. Just to clarify, reciprocal relationships are already being searched. That menu is populated by DISTINCT values in the relationship column of omoccurassociations.
> > > I am happy to add all reciprocal relationships; that's a good idea.
> > > To clarify even further, in the particular case of the db that was used in dev001, if you were to search using hostOf, there would be no results (i.e., we know for a fact that there are no entries in the omoccurassociations table with the hostOf relationship type, because it's not in the dropdown menu) EXCEPT those in the reciprocal hasHost relationship.
> > > You can essentially populate hostOf in that menu by adding such an association.
> > > But I agree... just to make things look better, I'll add reciprocals as well.
> > 
> > 
> > Ok, so if I'm understanding this correctly: the reason why it wasn't possible to search for hostOf was because there were no _occurrences_ in the db that is the host of another record, even though there are some records that have "hasHost" relationships?
> > I.e., all the occurrences with "hasHost" did not link to another occurrence?
> 
> Thank you for asking this question. It helped me realize that we really need that full complement of dropdown choices haha.
> 
> All it means is that there is no entry in the omoccurassociations table that has relationship 'hostOf'. It _doesn't_ mean that there are no occurrences with "hasHost" linked to another occurrence; there very well could be. And those occurrences should theoretically be captured in search results.
> 
> So, for instance, let's say there's an occurrence of Dendroctonus ponderosae that has a relationship of hasHost attached to another occurrence in the DB of a Pinus longifolia.
> 
> If you search for all taxa that hasHost Pinus longifolia, you should find that Dendroctonus ponderosae result.
> 
> Similarly, if you search for all taxa that are hostOf Dendroctonus ponderosae, you should find the Pinus longifolia occurrence.
> 
> Currently, and this is the bug at hand, if no other, random entry in omoccurassociations happens to explicitly have a hostOf relationship type, this
> 
> > if you search for all taxa that are hostOf Dendroctonus ponderosae, you should find the Pinus longifolia occurrence.
> 
> search won't be possible, because hostOf won't be the in drop down.
> 
> I hope I make sense and am thinking about this correctly. If not, no worries; we're in agreement regardless that this needs to be fixed haha.

Yes, when I carefully read your explanation, I think we're on the same page and it makes sense. Thanks!!

**Comment by Atticus29** [comment]
> I ran a search for Veratrum californicum ecologicallyOccursWith Veratrum speciosum
> 
> * [x]  include synonyms
> 
> I expected to find this record: https://dev001.symbiota.org/collections/individual/index.php?occid=2960592 Which is of Veratrum californicum and has an association with Veratrum californicum var. californicum, which is the accepted synonym of Veratrum speciosum.
> 
> I did not get any results, which seems to indicate that searching including synonyms is not working as expected.

Should be fixed in 3a8fd21b4.

**Comment by Atticus29** [comment]
Note to self: you will want to rebase this all into one commit before merging to make it easier to cherry pick given it's not likely 3.1 and it's going into the USDA more quickly.

**Comment by Atticus29** [comment]
> I think people will want to search by associations without having to specify a taxon name. For example, to answer the query: "What specimens are hosts of other species in this National Forest?" or "What specimens have multiple parts?" (i.e., has association type "partOf")
> 
> When I try to run this query, it just says "Associations-none" image

This should be fixed.

**Comment by Atticus29** [comment]
> I think that people will want to be able to search two taxa without specifying the associationType. Could we add "Any" to the dropdown menu and be able to search across multiple associationTypes?

This should be fixed.

**Comment by themerekat** [comment]
Thanks for your video about the known issue @Atticus29 . I think I like a version of your second recommendation: that whenever someone adds a relationship to omoccurassociations, the inverse is automatically added to the table.

I think the way it was written at first was very clever, since we didn't need all that redundant data, but if it's slowing down our search capabilities, that's a big problem. I'm already concerned with the minute or so that it already took that one query to run.

**Comment by themerekat** [comment]
Are text searches in associated taxon name (i.e., a name that isn't in the thesaurus) going to be allowed? If not, we should probably have error handling for when this happens (i.e., a pop-up that says "please select a name from the list"). I think it would be *best* if textual name searches were supported, but this might require indexing that we don't currently have set up (and also, could be a version 2 enhancement).

**Review by themerekat — CHANGES_REQUESTED** [review]
Looks like all my previous comments are fixed! Just see my previous comment about text searches, and we need to address your known issue.

**Comment by Atticus29** [comment]
> Are text searches in associated taxon name (i.e., a name that isn't in the thesaurus) going to be allowed? If not, we should probably have error handling for when this happens (i.e., a pop-up that says "please select a name from the list"). I think it would be _best_ if textual name searches were supported, but this might require indexing that we don't currently have set up (and also, could be a version 2 enhancement).

I think text searches are working?

**Comment by Atticus29** [comment]
> Looks like all my previous comments are fixed! Just see my previous comment about text searches, and we need to address your known issue.

Ok @themerekat . Text search *should* work now 🤞 . If still not, let's make it a version 2 enhancement.
You should also notice a performance improvement in terms of search speed now.
You should also see a button on the search results page if someone used the search-by-association accordion. It should be self-explanatory, but let me know if not. If the button breaks, it might be because of a known DB command that hasn't been run on dev001 yet, but let's try it without that first.

It might be interesting to test stuff BEFORE pressing that button and then testing again AFTER pressing the button.
I believe that reversions have been avoided, but I think it might be a good idea to run through the whole checklist of things you want working again just to make sure.

**Comment by themerekat** [comment]
Things to test:

- [x] Search for associations with a taxon name, associationType, association taxon name
- [Not passed, see comment after next one] Search for associations with stateProvince value, associationType, association taxon name
- [See comment after next one] Search for associations with bounding box, associationType, and association taxon name
- [traits not activated] Search for associations with taxon name, associationType, association taxon name, trait value
- [x] Conduct a search, then hit the back button --> the criteria are properly populated?
- [x] Search for ANY specimens with ANY association with "Apidae" (text, not matched in taxonomic thesaurus)
- [x] Search for association with taxon name, ANY association type, association taxon name (synonym of accepted name)

**Comment by themerekat** [comment]
When I add an association to a record, two associations are created instead of one. I think this is because one is displayed automatically from the inverse, and then _also_ one is created as the inverse, leading to 4 total associations (even though only 2 are needed and only 2 are in the database). The second one lacks some important metadata, but the first one also lacks the correct "Entered by" value, which is odd.
image

**Comment by themerekat** [comment]
I clicked the "populate inverse relationships" button and it just took me here:
image

P.S. Why is this a particular button? I thought these were going to be automatically generated when each association is added?

**Comment by themerekat** [comment]
With these criteria:
(subject Taxon was left empty, fwiw)
image

I got this record:
image

Which _has_ an association, but isn't itself an association (i.e., the inverse relationship does not exist, because it is a non-occurrence "Taxon Observation" association).

I would expect that the search would only result in any records for which _Abronia latifolia_ is the _object_ of the association.

That being said, I could see how the way that it currently works makes sense. If you're looking for things that are associated with _Abronia latifolia_, one of those things is "Apidae"...it's just not intuitive that Apidae is the subject of the association in this case. This might require some user feedback.

**Comment by themerekat** [comment]
Searching with these criteria:
image

Results in the not-working page of doom:
image

**Comment by themerekat** [comment]
> When I add an association to a record, two associations are created instead of one. I think this is because one is displayed automatically from the inverse, and then _also_ one is created as the inverse, leading to 4 total associations (even though only 2 are needed and only 2 are in the database). The second one lacks some important metadata, but the first one also lacks the correct "Entered by" value, which is odd.

Similarly, I think after I clicked the button to back-populate inverse relationships, I got a bunch of duplicate relationships:
image

**Comment by Atticus29** [comment]
> > When I add an association to a record, two associations are created instead of one. I think this is because one is displayed automatically from the inverse, and then _also_ one is created as the inverse, leading to 4 total associations (even though only 2 are needed and only 2 are in the database). The second one lacks some important metadata, but the first one also lacks the correct "Entered by" value, which is odd.
> 
> Similarly, I think after I clicked the button to back-populate inverse relationships, I got a bunch of duplicate relationships: image

Ok. I think I need to fix this. Noted. Thank you!

**Comment by Atticus29** [comment]
> Searching with these criteria: image
> 
> Results in the not-working page of doom: image

I wasn't expecting anyone to use taxon up top but not taxon in the association accordion. This is a bug. I'll fix.

**Comment by Atticus29** [comment]
> With these criteria: (subject Taxon was left empty, fwiw) image
> 
> I got this record: image
> 
> Which _has_ an association, but isn't itself an association (i.e., the inverse relationship does not exist, because it is a non-occurrence "Taxon Observation" association).
> 
> I would expect that the search would only result in any records for which _Abronia latifolia_ is the _object_ of the association.
> 
> That being said, I could see how the way that it currently works makes sense. If you're looking for things that are associated with _Abronia latifolia_, one of those things is "Apidae"...it's just not intuitive that Apidae is the subject of the association in this case. This might require some user feedback.

I'm not mad at this behavior, TBH. I think if we err on the side of giving people more results that kinda make sense than they might expect, that's way better than something missing that they expected. I would argue this is a feature rather than a bug...

**Comment by Atticus29** [comment]
> I clicked the "populate inverse relationships" button and it just took me here: image
> 
> P.S. Why is this a particular button? I thought these were going to be automatically generated when each association is added?

The button is to establish inverse records in the omoccurassociations table for any that already exist and don't have inverse records. It really should be a one-time button per portal. Maybe we move it to an admin page instead?

But you're right - for any new entry, this will not be a problem.

**Comment by Atticus29** [comment]
> When I add an association to a record, two associations are created instead of one. I think this is because one is displayed automatically from the inverse, and then _also_ one is created as the inverse, leading to 4 total associations (even though only 2 are needed and only 2 are in the database). The second one lacks some important metadata, but the first one also lacks the correct "Entered by" value, which is odd. image

I should fix these issues.

**Comment by Atticus29** [comment]
> I clicked the "populate inverse relationships" button and it just took me here: image
> 
> P.S. Why is this a particular button? I thought these were going to be automatically generated when each association is added?

If this button works successfully, it should take the user back to the search page with the criteria entered that they already used. Since it did not do this, I think that theres a bug. And I think I know what the bug is, because I had it locally and solved it with a DB patch. I notified @GregPost-ASU about it. Ed and Greg and I discussed it a little bit yesterday.

**Comment by themerekat** [comment]
> > I clicked the "populate inverse relationships" button and it just took me here: image
> > P.S. Why is this a particular button? I thought these were going to be automatically generated when each association is added?
> 
> The button is to establish inverse records in the omoccurassociations table for any that already exist and don't have inverse records. It really should be a one-time button per portal. Maybe we move it to an admin page instead?
> 
> But you're right - for any new entry, this will not be a problem.

Agreed about moving this to an admin page!

**Comment by Atticus29** [comment]
> > When I add an association to a record, two associations are created instead of one. I think this is because one is displayed automatically from the inverse, and then _also_ one is created as the inverse, leading to 4 total associations (even though only 2 are needed and only 2 are in the database). The second one lacks some important metadata, but the first one also lacks the correct "Entered by" value, which is odd. image
> 
> I should fix these issues.

Fixed in 1db4c587e. Now those search results on resourcetab.php ignore scriptGenerated omoccurassociation rows.

**Comment by Atticus29** [comment]
> > Searching with these criteria: image
> > Results in the not-working page of doom: image
> 
> I wasn't expecting anyone to use taxon up top but not taxon in the association accordion. This is a bug. I'll fix.

Fixed in 5f49faa64.

**Comment by Atticus29** [comment]
> > > I clicked the "populate inverse relationships" button and it just took me here: image
> > > P.S. Why is this a particular button? I thought these were going to be automatically generated when each association is added?
> > 
> > 
> > The button is to establish inverse records in the omoccurassociations table for any that already exist and don't have inverse records. It really should be a one-time button per portal. Maybe we move it to an admin page instead?
> > But you're right - for any new entry, this will not be a problem.
> 
> Agreed about moving this to an admin page!

Per subsequent conversations with Ed and Katie, we decided to remove this button entirely. Fixed in f33299eef.

**Comment by Atticus29** [comment]
> page of doom

No longer able to reproduce this on dev001. I can't remember whether I fixed it already or not.

**Comment by Atticus29** [comment]
> > > Searching with these criteria: image
> > > Results in the not-working page of doom: image
> > 
> > 
> > I wasn't expecting anyone to use taxon up top but not taxon in the association accordion. This is a bug. I'll fix.
> 
> Fixed in [5f49faa](https://github.com/BioKIC/Symbiota/commit/5f49faa64f96a0245c2b5921d9d179e5fc123d56).

Nvm. I did fix it.

**Comment by themerekat** [comment]
I think the SQL on the occurrence editor is incorrect, leading to listing tons of spurious associations. Should
"SELECT assocID, occid, associationType, occidAssociate, relationship, relationshipID, subType, objectID, basisOfRecord, resourceUrl, verbatimSciname, tid, locationOnHost, conditionOfAssociate, establishedDate, imageMapJSON, dynamicProperties, notes, accordingTo, instanceID, recordID, modifiedUid, modifiedTimestamp, createdUid, initialTimestamp FROM omoccurassociations WHERE basisOfRecord IS NULL OR basisOfRecord != 'scriptGenerated' AND (occid = 245874 OR occidAssociate = 245874)"

be

SELECT assocID .... FROM omoccurassociations WHERE **(**basisOfRecord IS NULL OR basisOfRecord != 'scriptGenerated'**)** AND (occid = 245874 OR occidAssociate = 245874)

**Comment by Atticus29** [comment]
> I think the SQL on the occurrence editor is incorrect, leading to listing tons of spurious associations. Should "SELECT assocID, occid, associationType, occidAssociate, relationship, relationshipID, subType, objectID, basisOfRecord, resourceUrl, verbatimSciname, tid, locationOnHost, conditionOfAssociate, establishedDate, imageMapJSON, dynamicProperties, notes, accordingTo, instanceID, recordID, modifiedUid, modifiedTimestamp, createdUid, initialTimestamp FROM omoccurassociations WHERE basisOfRecord IS NULL OR basisOfRecord != 'scriptGenerated' AND (occid = 245874 OR occidAssociate = 245874)"
> 
> be
> 
> SELECT assocID .... FROM omoccurassociations WHERE **(basisOfRecord IS NULL OR basisOfRecord != 'scriptGenerated')** AND (occid = 245874 OR occidAssociate = 245874)

@themerekat great catch and sleuthing. Fixed in 5de35bde5.

**Comment by themerekat** [comment]
Searching doesn't seem to be finding specimens with relationships of a certain taxon when the subject scientific name is blank. For example, I'm trying to find this record: /collections/individual/index.php?occid=2269041 using these criteria:
image
and I only get this one record that has _Mimulus guttatus_ as the _subject,_ not the object (associated taxon). 
image

Could this be because the scientific name isn't indexing when I first created the association?

**Comment by themerekat** [comment]
I think it might be misleading to have "None" as the default for the associations search because people might try to use it to mean "search for things of this taxon with NO associations". Maybe it should be re-worded to "Not specified" ?

image

**Comment by themerekat** [comment]
Searches that I've tested (checked boxes indicate that the function works as expected):
- [ ] only an object taxon (no subject) --> does not work as expected. See note above (2 comments ahead of this one)
- [x] ONLY a type of association
- [x] subject scientific name and an object scientific name
- [x] subject genus and object scientific name
- [ ] subject genus and object genus --> this one does NOT work. See note below.
- [ ] subject family and object scientific name --> unexpected results. See note below.
- [ ] subject family and object genus --> does NOT work. See note below.
- [x] subject family and object family
- [x] subject scientific name only
- [x] object scientific name only
- [x] subject scientific name, association type, and other details

**Comment by themerekat** [comment]
When I search for _Stanleya_ in the main taxonomic name and _Berteroa_ in the association's taxon name, it doesn't find this specimen record: https://dev001.symbiota.org/portal/collections/individual/index.php?occid=2175828&clid=0 , indicating that searching on the association's genus does not function the same way that searching on the main taxon's genus does. Either we should clarify this in the search form, or we should make sure that the search returns all children taxa of the association taxon as well.

**Comment by themerekat** [comment]
This was an unexpected search result. When I searched for all Brassicaceae (which is the family to which both _Stanleya_ and _Berteroa_ belong), I get these results:
image

The second record should not be included in these search results, however, because although it does match the "taxa" criterion, it does not match the "association taxon" criterion. The association taxon for this record is _Stanleya pinnata_ rather than _Berteroa incana_.

**Comment by themerekat** [comment]
> When I search for _Stanleya_ in the main taxonomic name and _Berteroa_ in the association's taxon name, it doesn't find this specimen record: https://dev001.symbiota.org/portal/collections/individual/index.php?occid=2175828&clid=0 , indicating that searching on the association's genus does not function the same way that searching on the main taxon's genus does. Either we should clarify this in the search form, or we should make sure that the search returns all children taxa of the association taxon as well.

Same problem when searching by subject Family and object genus. I think searching by genus in the object does not find all the children associations. For example, when you do this search:
image

There should be two records resulted:
image

Interestingly, you _do_ get these records if you search for just Brassicaeae and Brassicaceae, indicating that searching on the family is working, just not the object's genus.

**Comment by themerekat** [comment]
This may be the wrong branch on which to report this, but why is does this un-indexed name (i.e., name that is NOT in the taxonomic thesaurus) show up underlined on this page? It then links to _Arabis_, which is a related, but not equivalent taxon in the thesaurus.
image

**Comment by themerekat** [comment]
> Searching doesn't seem to be finding specimens with relationships of a certain taxon when the subject scientific name is blank. For example, I'm trying to find this record: /collections/individual/index.php?occid=2269041 using these criteria: image and I only get this one record that has _Mimulus guttatus_ as the _subject,_ not the object (associated taxon). image
> 
> Could this be because the scientific name isn't indexing when I first created the association?

Similar issue when I search for only _Berteroa incana_ as the object taxon, but for this one, I get one expected search result, but then one unexpected search result (the specimen whose subject is _Berteroa incana_).
image

**Comment by Atticus29** [comment]
> I think it might be misleading to have "None" as the default for the associations search because people might try to use it to mean "search for things of this taxon with NO associations". Maybe it should be re-worded to "Not specified" ?
> 
> image

Fixed in ea66d52b2.

**Comment by Atticus29** [comment]
> 2269041

@themerekat there is something a little weird with occurrence 2269041 in the omoccurassociations table on dev001: it has no occidAssociate:

Screenshot 2024-11-19 at 12 59 40 PM

This feels like a data problem rather than a search algorithm problem, but I don't know what the cause was or how to prevent it.

**Comment by themerekat** [comment]
> > 2269041
> 
> @themerekat there is something a little weird with occurrence 2269041 in the omoccurassociations table on dev001: it has no occidAssociate:
> 
> Screenshot 2024-11-19 at 12 59 40 PM
> This feels like a data problem rather than a search algorithm problem, but I don't know what the cause was or how to prevent it.

@Atticus29 , remember that there can be non-occurrence associations that are just associations with a taxonomic name. I think these would not have an occidAssociate.

**Comment by Atticus29** [comment]
> > > 2269041
> > 
> > 
> > @themerekat there is something a little weird with occurrence 2269041 in the omoccurassociations table on dev001: it has no occidAssociate:
> > Screenshot 2024-11-19 at 12 59 40 PM
> > This feels like a data problem rather than a search algorithm problem, but I don't know what the cause was or how to prevent it.
> 
> @Atticus29 , remember that there can be non-occurrence associations that are just associations with a taxonomic name. I think these would not have an occidAssociate.

How should we display them as results if they are not occurrences?

**Comment by themerekat** [comment]
> > > > 2269041
> > > 
> > > 
> > > @themerekat there is something a little weird with occurrence 2269041 in the omoccurassociations table on dev001: it has no occidAssociate:
> > > Screenshot 2024-11-19 at 12 59 40 PM
> > > This feels like a data problem rather than a search algorithm problem, but I don't know what the cause was or how to prevent it.
> > 
> > 
> > @Atticus29 , remember that there can be non-occurrence associations that are just associations with a taxonomic name. I think these would not have an occidAssociate.
> 
> How should we display them as results if they are not occurrences?

Hm, that is a good question...I don't think I've thought that far

**Comment by Atticus29** [comment]
> > > > > 2269041
> > > > 
> > > > 
> > > > @themerekat there is something a little weird with occurrence 2269041 in the omoccurassociations table on dev001: it has no occidAssociate:
> > > > Screenshot 2024-11-19 at 12 59 40 PM
> > > > This feels like a data problem rather than a search algorithm problem, but I don't know what the cause was or how to prevent it.
> > > 
> > > 
> > > @Atticus29 , remember that there can be non-occurrence associations that are just associations with a taxonomic name. I think these would not have an occidAssociate.
> > 
> > 
> > How should we display them as results if they are not occurrences?
> 
> Hm, that is a good question...I don't think I've thought that far

We're gonna have the same problem with results that are just iNat links. I've basically just not implemented anything yet for results that are not occurrences... 😓

**Comment by themerekat** [comment]
> > > > > > 2269041
> > > > > 
> > > > > 
> > > > > @themerekat there is something a little weird with occurrence 2269041 in the omoccurassociations table on dev001: it has no occidAssociate:
> > > > > Screenshot 2024-11-19 at 12 59 40 PM
> > > > > This feels like a data problem rather than a search algorithm problem, but I don't know what the cause was or how to prevent it.
> > > > 
> > > > 
> > > > @Atticus29 , remember that there can be non-occurrence associations that are just associations with a taxonomic name. I think these would not have an occidAssociate.
> > > 
> > > 
> > > How should we display them as results if they are not occurrences?
> > 
> > 
> > Hm, that is a good question...I don't think I've thought that far
> 
> We're gonna have the same problem with results that are just iNat links. I've basically just not implemented anything yet for results that are not occurrences... 😓

Yeah, I think that will be the next evolution of the search. Just producing occurrence results might be the extent of what we can do right now.

**Comment by Atticus29** [comment]
> When I search for _Stanleya_ in the main taxonomic name and _Berteroa_ in the association's taxon name, it doesn't find this specimen record: https://dev001.symbiota.org/portal/collections/individual/index.php?occid=2175828&clid=0 , indicating that searching on the association's genus does not function the same way that searching on the main taxon's genus does. Either we should clarify this in the search form, or we should make sure that the search returns all children taxa of the association taxon as well.

Ok. I believe I have fixed this issue in e26800cb5. It feels like a hacky fix, but it seems to be working?

**Comment by Atticus29** [comment]
> This was an unexpected search result. When I searched for all Brassicaceae (which is the family to which both _Stanleya_ and _Berteroa_ belong), I get these results: image
> 
> The second record should not be included in these search results, however, because although it does match the "taxa" criterion, it does not match the "association taxon" criterion. The association taxon for this record is _Stanleya pinnata_ rather than _Berteroa incana_.

I think that the results are currently going to return both samples in the relationship no matter what (because it's not possible to know in which direction the original association record was made). So, in a sense, a "self" result is expected. I can't think of a way to solve this problem in the query. I'll think about it more, but I don't know that this is solvable if we don't know which direction the original relationship was created (i.e., was the association created in the Berteroa incana occurrence or in the Stanleya pinnata occurrence?).

**Comment by Atticus29** [comment]
> > When I search for _Stanleya_ in the main taxonomic name and _Berteroa_ in the association's taxon name, it doesn't find this specimen record: https://dev001.symbiota.org/portal/collections/individual/index.php?occid=2175828&clid=0 , indicating that searching on the association's genus does not function the same way that searching on the main taxon's genus does. Either we should clarify this in the search form, or we should make sure that the search returns all children taxa of the association taxon as well.
> 
> Same problem when searching by subject Family and object genus. I think searching by genus in the object does not find all the children associations. For example, when you do this search: image
> 
> There should be two records resulted: image
> 
> Interestingly, you _do_ get these records if you search for just Brassicaeae and Brassicaceae, indicating that searching on the family is working, just not the object's genus.

This looks to be solved by commit e26800cb5 as well.

**Comment by Atticus29** [comment]
> This may be the wrong branch on which to report this, but why is does this un-indexed name (i.e., name that is NOT in the taxonomic thesaurus) show up underlined on this page? It then links to _Arabis_, which is a related, but not equivalent taxon in the thesaurus. image

Can we create a separate issue for this and solve it separately, if only for my personal sanity?

**Comment by Atticus29** [comment]
> > Searching doesn't seem to be finding specimens with relationships of a certain taxon when the subject scientific name is blank. For example, I'm trying to find this record: /collections/individual/index.php?occid=2269041 using these criteria: image and I only get this one record that has _Mimulus guttatus_ as the _subject,_ not the object (associated taxon). image
> > Could this be because the scientific name isn't indexing when I first created the association?
> 
> Similar issue when I search for only _Berteroa incana_ as the object taxon, but for this one, I get one expected search result, but then one unexpected search result (the specimen whose subject is _Berteroa incana_). image

This is the same problem of having to return the other partner in the association, because we can't know in which direction the association record was created. I.e., not sure if solvable if we can't know that information.

**Review by themerekat — APPROVED** [review]

**Pull request merged**
